version: "3.9"
services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_PORT=2181
      - ZOO_SERVERS=server.1=zoo1:2888:3888
  kafka:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="shipment-verified:1:3, shipment-sent:1:1"
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  manufacturer:
    image: manufacturer
    ports:
      - "3001:3000"
    environment:
      - KAFKA_ADDRESS=kafka:9092
    depends_on:
      - kafka
  authority:
    image: authority
    ports:
      - "3002:3000"
    environment:
      - KAFKA_ADDRESS=kafka:9092
    depends_on:
      - kafka
      - manufacturer
  customer:
    image: customer
    ports:
      - "3003:3000"
    environment:
      - KAFKA_ADDRESS=kafka:9092
    depends_on:
      - kafka
      - manufacturer
